import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useState } from 'react'

type Props = {
  report: string
  sourcesUsed: number
  query: string
  onReset: () => void
}

export function ReportView({ report, sourcesUsed, query, onReset }: Props) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExport = () => {
    const blob = new Blob([report], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `research-${Date.now()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="py-6">
      {/* Report header */}
      <div className="flex items-start justify-between gap-4 mb-6 pb-5 border-b border-[#1e1e2e]">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
            <span className="text-xs text-emerald-600 font-medium uppercase tracking-widest">
              Research complete
            </span>
          </div>
          <h2 className="text-base font-semibold text-slate-200 mb-1">
            {query}
          </h2>
          <p className="text-xs text-slate-600">
            {sourcesUsed} sources analysed · compiled by GPT-4o
          </p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 flex-shrink-0">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 text-xs bg-[#13131f] hover:bg-[#1e1e2e]
              text-slate-400 hover:text-slate-200 rounded-lg border border-[#2d2d3d]
              hover:border-slate-600 transition-all"
          >
            {copied ? '✓ Copied' : 'Copy'}
          </button>
          <button
            onClick={handleExport}
            className="px-3 py-1.5 text-xs bg-[#13131f] hover:bg-[#1e1e2e]
              text-slate-400 hover:text-slate-200 rounded-lg border border-[#2d2d3d]
              hover:border-slate-600 transition-all"
          >
            Export .md
          </button>
          <button
            onClick={onReset}
            className="px-3 py-1.5 text-xs bg-indigo-600 hover:bg-indigo-500
              text-white rounded-lg transition-all active:scale-95"
          >
            New research
          </button>
        </div>
      </div>

      {/* Report body */}
      <div className="report-content">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {report}
        </ReactMarkdown>
      </div>

      {/* Footer */}
      <div className="mt-10 pt-5 border-t border-[#1e1e2e] flex items-center justify-between">
        <p className="text-xs text-slate-700">
          Generated by ResearchMind · Multi-agent AI
        </p>
        <button
          onClick={onReset}
          className="text-xs text-indigo-500 hover:text-indigo-400 transition-colors"
        >
          ← New research
        </button>
      </div>
    </div>
  )
}